// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.fuchsia:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.windows:
        // TODO: Handle this case.
        throw UnimplementedError();
    }

    // ignore: dead_code
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTCz4JIAKu-SONCefaBVFyT2vUKZtA1o',
    appId: '1:886916492439:web:6b3255d12320a6f8bd0dd2',
    messagingSenderId: '886916492439',
    projectId: 'hotella-c439e',
    authDomain: 'hotella-c439e.firebaseapp.com',
    storageBucket: 'hotella-c439e.appspot.com',
    measurementId: 'G-PJ3C6GQ2TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyT1nxMYv2ZegGIint4ZLlc_6o4nI7HZ8',
    appId: '1:886916492439:android:24d284a0e269ee45bd0dd2',
    messagingSenderId: '886916492439',
    projectId: 'hotella-c439e',
    storageBucket: 'hotella-c439e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwv3XLsYgD0X9ljm_wQHRqnAQYMqINlWM',
    appId: '1:886916492439:ios:cbffa53bc4aec12ebd0dd2',
    messagingSenderId: '886916492439',
    projectId: 'hotella-c439e',
    storageBucket: 'hotella-c439e.appspot.com',
    iosClientId: '886916492439-tnm3b7the8b3h5tjohmqnpit2dev121h.apps.googleusercontent.com',
    iosBundleId: 'com.novel.hotellnaadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwv3XLsYgD0X9ljm_wQHRqnAQYMqINlWM',
    appId: '1:886916492439:ios:cbffa53bc4aec12ebd0dd2',
    messagingSenderId: '886916492439',
    projectId: 'hotella-c439e',
    storageBucket: 'hotella-c439e.appspot.com',
    iosClientId: '886916492439-tnm3b7the8b3h5tjohmqnpit2dev121h.apps.googleusercontent.com',
    iosBundleId: 'com.novel.hotellnaadmin',
  );
}
